{
 "title": "Sensor values",
 "time": { "from": "now-8h", "to": "now" },
 "panels": [
  {
   "title": "Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 22, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (sen.sensor_id)\nsen.sensor_id,\nvalue, \nlatitude, \nlongitude\nFROM sensordatavalues as sen \nINNER JOIN \nlocation as loc \nON \nsen.sensor_id = loc.sensor_id \nWHERE sen.value_type = 'P1' AND sen.value < 1000\nORDER BY sen.sensor_id, (sen.time+sen.date) DESC"
    }
   ]
  },
  {
   "title": "Median of all sensor values",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time_bucket('30 minutes', (time+date)) AS \"time\",\n  median(value),\n  value_type\nfrom sensordatavalues\nWHERE (value_type = 'P1' OR value_type = 'P2') AND $__timeFilter(time+date)\nGROUP BY 1, value_type\nORDER BY 1 ASC;\n"
    }
   ]
  },
  {
   "title": "Selected sensor 14326",
   "type": "graph",
   "description": "Shows value of a selected sensor.",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  value,\n  $__time(time + date),\n  value_type\nFROM\n  sensordatavalues\nWHERE (value_type = 'P1' OR value_type = 'P2') AND sensor_id = 56253 AND $__timeFilter(time+date) \nORDER BY time + date ASC \n"
    }
   ]
  }
 ]
}